In [1]:
import os
from dotenv import load_dotenv
import pandas as pd

In [2]:
load_dotenv("../.env")
data_path = os.getenv("accepted_data_path")

In [3]:
cols = ["id", "loan_amnt", "term", "int_rate", "grade", "emp_length",
    "home_ownership", "annual_inc", "verification_status", "purpose",
    "dti", "delinq_2yrs", "earliest_cr_line", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "revol_util", "total_acc",
    "issue_d", "loan_status"]

In [4]:
df = pd.read_csv(data_path, usecols=cols, low_memory=False)

In [5]:
df.head()

,id,loan_amnt,term,int_rate,grade,emp_length,home_ownership,annual_inc,verification_status,issue_d,...,purpose,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,open_acc,pub_rec,revol_bal,revol_util,total_acc
0,68407277,3600.0,36 months,13.99,C,10+ years,MORTGAGE,55000.0,Not Verified,Dec-2015,...,debt_consolidation,5.91,0.0,Aug-2003,1.0,7.0,0.0,2765.0,29.7,13.0
1,68355089,24700.0,36 months,11.99,C,10+ years,MORTGAGE,65000.0,Not Verified,Dec-2015,...,small_business,16.06,1.0,Dec-1999,4.0,22.0,0.0,21470.0,19.2,38.0
2,68341763,20000.0,60 months,10.78,B,10+ years,MORTGAGE,63000.0,Not Verified,Dec-2015,...,home_improvement,10.78,0.0,Aug-2000,0.0,6.0,0.0,7869.0,56.2,18.0
3,66310712,35000.0,60 months,14.85,C,10+ years,MORTGAGE,110000.0,Source Verified,Dec-2015,...,debt_consolidation,17.06,0.0,Sep-2008,0.0,13.0,0.0,7802.0,11.6,17.0
4,68476807,10400.0,60 months,22.45,F,3 years,MORTGAGE,104433.0,Source Verified,Dec-2015,...,major_purchase,25.37,1.0,Jun-1998,3.0,12.0,0.0,21929.0,64.5,35.0

In [6]:
df.shape

(2260701, 21)

In [7]:
df.columns

Index(['id', 'loan_amnt', 'term', 'int_rate', 'grade', 'emp_length',
       'home_ownership', 'annual_inc', 'verification_status', 'issue_d',
       'loan_status', 'purpose', 'dti', 'delinq_2yrs', 'earliest_cr_line',
       'inq_last_6mths', 'open_acc', 'pub_rec', 'revol_bal', 'revol_util',
       'total_acc'],
      dtype='str')

In [8]:
df["loan_status"].value_counts()

loan_status
Fully Paid                                             1076751
Current                                                 878317
Charged Off                                             268559
Late (31-120 days)                                       21467
In Grace Period                                           8436
Late (16-30 days)                                         4349
Does not meet the credit policy. Status:Fully Paid        1988
Does not meet the credit policy. Status:Charged Off        761
Default                                                     40
Name: count, dtype: int64

In [9]:
keep = ["Fully Paid", "Charged Off", "Default"]
df = df[df["loan_status"].isin(keep)].copy()

In [10]:
df["target"] = (df["loan_status"] != "Fully Paid").astype(int)

In [11]:
df["issue_d"] = pd.to_datetime(df["issue_d"], format="%b-%Y")
df["year"] = df["issue_d"].dt.year

In [12]:
df.head()

,id,loan_amnt,term,int_rate,grade,emp_length,home_ownership,annual_inc,verification_status,issue_d,...,delinq_2yrs,earliest_cr_line,inq_last_6mths,open_acc,pub_rec,revol_bal,revol_util,total_acc,target,year
0,68407277,3600.0,36 months,13.99,C,10+ years,MORTGAGE,55000.0,Not Verified,2015-12-01,...,0.0,Aug-2003,1.0,7.0,0.0,2765.0,29.7,13.0,0,2015
1,68355089,24700.0,36 months,11.99,C,10+ years,MORTGAGE,65000.0,Not Verified,2015-12-01,...,1.0,Dec-1999,4.0,22.0,0.0,21470.0,19.2,38.0,0,2015
2,68341763,20000.0,60 months,10.78,B,10+ years,MORTGAGE,63000.0,Not Verified,2015-12-01,...,0.0,Aug-2000,0.0,6.0,0.0,7869.0,56.2,18.0,0,2015
4,68476807,10400.0,60 months,22.45,F,3 years,MORTGAGE,104433.0,Source Verified,2015-12-01,...,1.0,Jun-1998,3.0,12.0,0.0,21929.0,64.5,35.0,0,2015
5,68426831,11950.0,36 months,13.44,C,4 years,RENT,34000.0,Source Verified,2015-12-01,...,0.0,Oct-1987,0.0,5.0,0.0,8822.0,68.4,6.0,0,2015

In [13]:
df["target"].value_counts()

target
0    1076751
1     268599
Name: count, dtype: int64

In [14]:
df["year"].value_counts()

year
2015    375546
2016    293105
2014    223103
2017    169321
2013    134804
2018     56318
2012     53367
2011     21721
2010     11536
2009      4716
2008      1562
2007       251
Name: count, dtype: int64

In [18]:
%pip install pyarrow

Collecting pyarrow
  Downloading pyarrow-25.0.1-cp311-cp311-win_amd64.whl.metadata (3.0 kB)
Downloading pyarrow-25.0.1-cp311-cp311-win_amd64.whl (27.9 MB)
   ---------------------------------------- 0.0/27.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.9 MB ? eta -:--:--
   - -------------------------------------- 0.8/27.9 MB 4.8 MB/s eta 0:00:06
   --- ------------------------------------ 2.4/27.9 MB 6.7 MB/s eta 0:00:04
   ------ --------------------------------- 4.5/27.9 MB 7.9 MB/s eta 0:00:03
   ------------ --------------------------- 8.7/27.9 MB 11.2 MB/s eta 0:00:02
   ----------------- ---------------------- 12.1/27.9 MB 12.2 MB/s eta 0:00:02
   -------------------- ------------------- 14.4/27.9 MB 12.1 MB/s eta 0:00:02
   ------------------------- -------------- 17.6/27.9 MB 12.4 MB/s eta 0:00:01
   ------------------------------ --------- 21.5/27.9 MB 13.3 MB/s eta 0:00:01
   ----------------------------------- ---- 24.4/27.9 MB 13.4 MB/s eta 0:00:01
   ---------------------------------------  27.3/27.9 MB 13.4 MB/s eta 0:00:01
   ---------------------------------------- 27.9/27.9 MB 12.3 MB/s  0:00:02
Installing collected packages: pyarrow
Successfully installed pyarrow-25.0.1
Note: you may need to restart the kernel to use updated packages.

In [15]:
df.to_parquet(r"E:/coding/PROJECTS/Credit_Risk_System/data/filtered.parquet", index=False)